app:
  origin: '*'

server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  host: '127.0.0.1'
  database: 'db-todo-it'
  username: 'postgres'
  password: '1313'
  migrationsRun: false
  logging: true

jwt:
  tokenLife: 3600
  refreshTokenLife: 86400
  secret: secret
googleAuth:
  GOOGLE_REDIRECT_URL: 'http://localhost:3000/auth/google-redirect'
  GOOGLE_AUTH_CLIENT_ID: '511298285211-tljvs2vs6c89usmrubp7kqi3493fuqce.apps.googleusercontent.com'
  GOOGLE_AUTH_SECRET: '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'
