app:
  origin: '*'

server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  host: '127.0.0.1'
  database: 'db-todo-it'
  username: 'postgres'
  password: '1313'
  migrationsRun: false
  logging: true

jwt:
  tokenLife: 3600
  refreshTokenLife: 86400
  secret: secret
googleAuth:
  GOOGLE_REDIRECT_URL: 'http://localhost:3000/auth/google-redirect'
  GOOGLE_AUTH_CLIENT_ID: '511298285211-tljvs2vs6c89usmrubp7kqi3493fuqce.apps.googleusercontent.com'
  GOOGLE_AUTH_SECRET: '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'
  FE_REDIRECT_URL: 'http://localhost:4200/auth/tokens'

mailgun:
  MAILGUN_USERNAME: 'postmaster@sandboxcb8a5d7373ca4da1860bb914676d8b13.mailgun.org'
  MAILGUN_KEY: 'key-ee6a36cb997de13fdd7c99daa69a1672'
  MAILGUN_PUBLIC_KEY: 'pubkey-96eec1acd8dc70118a22e9f50e6f8445'
  MAILGUN_HOST: 'smtp:mailgun:org'
  MAILGUN_PASSWORD: '3d90f5002ec81e4d75de3906c35df284'
